// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: weather_only

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H


#endif
